# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/kanas3gnfcxx/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/npsmobex:system/bin/npsmobex \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/hostapd:system/bin/hostapd \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/engpc:system/bin/engpc \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libsamsungearcare.so:system/lib/libsamsungearcare.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libsamsungeffect.so:system/lib/libsamsungeffect.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libSamsungPkcs11Wrapper.so:system/lib/libSamsungPkcs11Wrapper.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/dhcpcd/dhcpcd.conf:system/etc/dhcpcd/dhcpcd.conf \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/dhcpcd/dhcpcd-run-hooks:system/etc/dhcpcd/dhcpcd-run-hooks \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/dhcpcd/dhcpcd-hooks/20-dns.conf:system/etc/dhcpcd/dhcpcd-hooks/20-dns.conf \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/dhcpcd/dhcpcd-hooks/95-configured:system/etc/dhcpcd/dhcpcd-hooks/95-configured \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/media_codecs.xml:system/etc/media_codecs.xml \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/media_profiles.xml:system/etc/media_profiles.xml \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libsprd_agps_agent.so:system/lib/libsprd_agps_agent.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/hw/nfc_nci.sc7735s.so:system/lib/hw/nfc_nci.sc7735s.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libMali.so:system/lib/libMali.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/egl/libEGL_mali.so:system/lib/egl/libEGL_mali.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/egl/libGLESv1_CM_mali.so:system/lib/egl/libGLESv1_CM_mali.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/egl/libGLESv2_mali.so:system/lib/egl/libGLESv2_mali.so \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/audio_hw.xml:system/etc/audio_hw.xml \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/default_gain.conf:system/etc/default_gain.conf \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/audio_para:system/etc/audio_para \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/audio_policy.conf:system/etc/audio_policy.conf \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/codec_pga.xml:system/etc/codec_pga.xml \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/tiny_hw.xml:system/etc/tiny_hw.xml \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/modules/dhd.ko:system/lib/modules/dhd.ko \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/wifi/bcmdhd_apsta.bin:system/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/wifi/bcmdhd_sta.bin:system/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/wifi/bcmdhd_mfg.bin:system/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/wifi/nvram_net.txt:system/etc/wifi/nvram_net.txt \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/wifi/nvram_mfg.txt:system/etc/wifi/nvram_mfg.txt \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/wifi/bcmdhd_p2p.bin:system/etc/wifi/bcmdhd_p2p.bin \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/libnfc-brcm.conf:system/etc/libnfc-brcm.conf \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/libnfc-nxp.conf:system/etc/libnfc-nxp.conf \

PRODUCT_COPY_FILES += \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/nfcee_access.xml:system/etc/nfcee_access.xml \
    vendor/samsung/kanas3gnfcxx/proprietary/etc/migrate_nfc.txt:system/etc/migrate_nfc.txt \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/kanas3gnfcxx/proprietary/vendor/firmware/BCM4330B1_002.001.003.1025.1303.hcd:system/vendor/firmware/BCM4330B1_002.001.003.1025.1303.hcd \
    vendor/samsung/kanas3gnfcxx/proprietary/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/dhcpcd:system/bin/dhcpcd \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/librilutils.so:system/lib/librilutils.so \
    vendor/samsung/kanas3gnfcxx/proprietary/framework/com.broadcom.nfc.jar:system/framework/com.broadcom.nfc.jar

    # vendor/samsung/kanas3gnfcxx/proprietary/framework/com.android.nfc_extras.jar:system/framework/com.android.nfc_extras.jar\
    # vendor/samsung/kanas3gnfcxx/proprietary/framework/com.gsma.services.nfc.jar:system/framework/com.gsma.services.nfc.jar\

PRODUCT_COPY_FILES += \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libisp.so:system/lib/libisp.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libAMSWiFiLibs-1.0.6.so:system/lib/libAMSWiFiLibs-1.0.6.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libtwifingr.so:system/lib/libtwifingr.so

    # vendor/samsung/kanas3gnfcxx/proprietary/lib/libnfc-nci.so:system/lib/libnfc-nci.so \
    # vendor/samsung/kanas3gnfcxx/proprietary/lib/libnfc_nci_jni.so:system/lib/libnfc_nci_jni.so \

PRODUCT_COPY_FILES += \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libswiftkeysdk-java.so:system/lib/libswiftkeysdk-java.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libwpa_client.so:system/lib/libwpa_client.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/hw/camera2.sc8830.so:system/lib/hw/camera2.sc8830.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libwvm.so:system/lib/libwvm.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libomafldrm.so:system/lib/libomafldrm.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/drm/libdrmwvmplugin.so:system/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/drm/libomaplugin.so:system/lib/drm/libomaplugin.so \
    vendor/samsung/kanas3gnfcxx/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/kanas3gnfcxx/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
    vendor/samsung/kanas3gnfcxx/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/kanas3gnfcxx/proprietary/bin/lpm:system/bin/lpm \
    vendor/samsung/kanas3gnfcxx/proprietary/lib/libQmageDecoder.so:system/lib/libQmageDecoder.so \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_5.qmg:system/media/battery_charging_5.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_10.qmg:system/media/battery_charging_10.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_15.qmg:system/media/battery_charging_15.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_20.qmg:system/media/battery_charging_20.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_25.qmg:system/media/battery_charging_25.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_30.qmg:system/media/battery_charging_30.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_35.qmg:system/media/battery_charging_35.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_40.qmg:system/media/battery_charging_40.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_45.qmg:system/media/battery_charging_45.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_50.qmg:system/media/battery_charging_50.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_55.qmg:system/media/battery_charging_55.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_60.qmg:system/media/battery_charging_60.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_65.qmg:system/media/battery_charging_65.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_70.qmg:system/media/battery_charging_70.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_75.qmg:system/media/battery_charging_75.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_80.qmg:system/media/battery_charging_80.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_85.qmg:system/media/battery_charging_85.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_90.qmg:system/media/battery_charging_90.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_95.qmg:system/media/battery_charging_95.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_charging_100.qmg:system/media/battery_charging_100.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_batteryerror.qmg:system/media/battery_batteryerror.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/battery_error.qmg:system/media/battery_error.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/chargingwarning.qmg:system/media/chargingwarning.qmg \
    vendor/samsung/kanas3gnfcxx/proprietary/media/Disconnected.qmg:system/media/Disconnected.qmg
